### ISSUE TITLE
RtiFactoryFactory with Java 9

### ISSUE THREAD

**Issue by EMostafaAli** [openlvc/portico#204]
According to [Java 9 documentation](https://docs.oracle.com/javase/9/docs/api/javax/imageio/spi/ServiceRegistry.html), ServiceRegistry class can be used only with standard Image I/O service.
This means the following code won't work (I tried it myself)
 try {
           RtiFactory rtiFactory = RtiFactoryFactory.getRtiFactory();
            System.out.println(rtiFactory.rtiName());
        } catch (RTIinternalError rtIinternalError) {
            rtIinternalError.printStackTrace();
        }

Does this means we have to implement our own RtiFactoryFactory that uses ServiceLoader?

**Comment by timpokorny** [comment]
G'day @EMostafaAli,

Short answer is that I'm not sure. I haven't thought at all about it yet. We're only building to Java 8 at the moment. Java 9 itself isn't an LTS release and is only supported for another few months (through until March I think). The use of the `ServiceRegistry` is something in the standard, so I'm not sure what the right approach is to address this. I will likely just hack around it for the internals I think. Leave it with me to look at.

Cheers,
Tim

**Comment by timpokorny** [comment]
H'ok. So I've just done the naughty thing and hard coded the various Portico implementations into the standard classes. Not really a big deal because it's all hidden behind them and if switching RTI implementations you'll be switching the implementations of the standard classes as well. Fingers crossed this is the end of an awful decision to make things needlessly complicated in the standard.

**Comment by EMostafaAli** [comment]
Hi Tim,

Honestly, I am not sure if this is the "ideal" solution, imagine the following scenario:

1. Someone developed a federate while referencing the standard interfaces.
2. At run time, he/she adds portico lib

Not sure, if it will work correctly.

**Comment by timpokorny** [comment]
That should work just fine, because these changes are behind the façade of the standard interfaces. Any calls made to them will be resolved at runtime, so if the Portico libs are on the path, it’ll use the “Portico flavoured” implementation which will create Portico classes. If another RTI is on the path, it’ll use those.

The only thing a user will not be able to do now is register their own custom time implementations, which I still to this day cannot see a good use for (that warrants forcing the problem on to every user). So unless someone has a specific need for custom time types, everything should be fine. And if they do have a specific need for custom time types… Portico would still fritz because it wants to cast to a standard (double or long) type internally anyway, so no loss!
