### ISSUE TITLE
Port the MomManager to the new centralized RTIExec

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#230]
Summary
----
Port the `MomManager` to the new centralized `rtiexec`. This includes the necessary infrastructure updates and the ability for the manager to catch relevant federation lifecycle events and requests for updates from federates, sending object registration an

 - Publish an instance of `HLAfederation` for the federation
 - Publish an instance of `HLAfederate` for each federate that joins the federation
 - Catch requests to update attribute values for these objects
 - Generate reflections for those requests

Acceptance Criteria
----
Once complete, Portico shall:

- [x] `MomManager` ported to centralized RTI executive
- [x] RTI Exec will publish an instance of `HLAfederation` for the federation
- [x] RTI Exec will publish an instance of `HLAfederate` for each federate that joins the federation
- [x] `MomManager` will catch all relevant federate join/resign and change calls to maintain `HLAfederate` state
- [x] `MomManager` will receive requests to update attribute values for MOM instances and send reflections in response
- [ ] be able to confirm this functionality through the existing unit test suites
- [ ] be able to confirm this functionality through the example 1516e federate

**Comment by michaelrfraser** [comment]
I'm fairly close now to rounding out this feature.

A `MomManager` for the new centralized RTI has been put in place. The instance lives within the RTI's Federation class and creates a HLAFederation that mirrors it. As federates join, new HLAFederate objects are added to the Federation's object `Repository`, so that ordinary federates can discover them.

The RTI handler code for `RequestObjectUpdate` has been modified to route requests for any `HLAFederation` or `HLAFederate` objects to the `MomManager` which will generate an appropriate `ReflectAttributeValues` message for them (ordinarily these requests would be forwarded to the federate that owns the objects).

Code to serialize the values of all previously supported `HLAFederation` and `HLAFederate` attributes has 
been ported over. In some cases the encoding needed to be fixed to be standard compliant (Handles and Time Values are actually `HLAvariableArray`s of `HLAbyte` not just a plain HLAinteger64BE etc.

I've also added metric tracking for the following Federate attributes:

- HLAreflectionsReceived
- HLAupdatesSent
- HLAinteractionsReceived
- HLAinteractionsSent
- HLAobjectInstancesThatCanBeDeleted
- HLAobjectInstancesUpdated
- HLAobjectInstancesReflected
- HLAobjectInstancesDeleted
- HLAobjectInstancesRemoved
- HLAobjectInstancesRegistered
- HLAobjectInstancesDiscovered

All of these metrics are contained in the class `FederateMetrics`, which is saved against the RTI `Federate` object. While these weren't part of the original request, they are essential for the subsequent MOM Request/Report interactions that need to be implemented, so it felt like an appropriate time to add them.

Everything looks to be working ok using the test federate that Tim provided. The next steps will be to run the unit tests over the new code, and to do some final documentation and cleanup.

Having already spent the whole of last week on the task, I would estimate that there's about 1 day left of work to finish this off.

**Comment by michaelrfraser** [comment]
Work for this task has been completed. PR submitted to #270

**Comment by michaelrfraser** [comment]
PR has been merged into branch port219-central-rti.

Closing ticket
