### ISSUE TITLE
MOM support for service invocation information and exceptions

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#237]
Summary
----
Add support for the following calls MOM request/report interactions:

- Report:  `HLAreportException`
- Report:  `HLAreportServiceInvocation`
- Report:  `HLAreportMOMexception`
- Report:  `HLAreportFederateLost`

Acceptance Criteria
----
Once complete, Portico shall:

- [ ] be able to confirm this functionality through the existing unit test suites

**Comment by michaelrfraser** [comment]
@tpr1 just wondering if you can give me some guidance as to what you will be using the HLAreportServiceInvocation notification for? Do you require the parameters that the service was invoked with, or just the name of the service itself?

**Comment by tpr1** [comment]
I have no plans to use the supplied or returned arguments.

I am worried about deadlock situations that arise due to poorly configured federates. For instance, a federate might sit in a loop waiting for a receive order message that will never arrive because all its peers who publish that message have sent an advance time request. The HLAreportServiceInvocation could be used as an interrupt flag to trigger some recovery action in cases where deadlock is possible; it would really only need the service name and success indicator for that purpose.

**Comment by michaelrfraser** [comment]
Thanks Thomas, will get onto it straight away!

**Comment by timpokorny** [comment]
Merged!
