### ISSUE TITLE
What about a filter in the WAN router?

### ISSUE THREAD

**Issue by icemagno** [openlvc/portico#305]
Hi Tim.
I'm working on a Federation running the RPR FOM and recently read a paper about security in sharing simulation details of military stuff. My country was a site in Vicking 18 exercice and I am thinking if the WAN router can have some configurations to filter classes and interaction somehow. 

What do you think?

**Comment by timpokorny** [comment]
G'day Carlos,

Filtering at the WAN router level would certainly provide some capability to adjust traffic flows. That said, the root issue here is typically not technology, but certification. The practical reality for these types of applications though is that they need to go through a lot more scrutiny before they're certified to be used in a cross-security-domain context. That's why there are so few gateways that do this out there. Expensive to build and get through the process, so it's only done by a few. I know a Pitch tool was used for Viking to do this and Pitch spent a long time co-developing that tool with to Swedish Army requirements to get the necessary certifications.

So, technically possible, but practically difficult I would say.

**Comment by icemagno** [comment]
Understood... can you delete this? I think this is not a issue... There is another place to ask you such things?

**Comment by timpokorny** [comment]
@icemagno - Here is fine. I can look for a way to remove the content if you want but everything is here is well and truly public info so I can't see any concern. Up to you. Let me know.

**Comment by icemagno** [comment]
Hi Tim, I know you're  a busy guy. You have made a wonderful work here. I do not feel very well having a very good free product and yet having your free support. I think free must be as-is and support must be pay. But... I confess is too hard to put some things not related to HLA itself to work because is too portoco specific.

But I'll try to fight by myself as long as I can without asking for help. Be sure if I ask for help it will be because I really  can't figure out.

BRAVO ZULU Tim.

**Comment by timpokorny** [comment]
All good. Just trying to fit things in between work 👍
