### ISSUE TITLE
HLA 1.3 C++ tests (with GCC) use deprecated string transformation

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#99]
When compiling the HLA 1.3 unit tests with GCC they generate an absolute avalanche of warnings, all pretty much of the following variety:

`ParameterHandleValuePairSetTest.cpp:249: warning: deprecated conversion from string constant to 'char*'`

Go through and clean all these up because they're annoying on both Linux and MacOS X

**Comment by michaelrfraser** [comment]
Hey @timpokorny,

Felt guilty that I haven't really done anything in the past X years so I picked this one because it looked like a good issue to get my feet wet with.

I've currently got my repo set up as a fork of the openlvc master, with it set up as the remote upstream. I cannot for the life of me find a linux cpp build profile however :( I've tried looking on upstream/master and upstream/maintenance-2.0.x, however the linux profile directory looks to only have java related things in it.

Running `./ant cpp.compile` yields the following:

````
Buildfile: /home/michael/Documents/dev/workspace/portico/codebase/build.xml
     [echo] Build Version: portico-2.1.0-dev (build 0)
 [platform] Operating System platform is: linux64

cpp.compile:

BUILD SUCCESSFUL
Total time: 0 seconds
````

So just wondering if there's a particular branch this issue exists on, or has the issue been subsumed over time?

PS: No string errors found on OSX using Clang as far as I can see.

**Comment by timpokorny** [comment]
@michaelrfraser - profile is located in [`hla13.xml`](https://github.com/openlvc/portico/blob/master/codebase/profiles/linux/hla13.xml#L74). From memory it doesn't complain on OS X because I turn the warning off for the compiler :sa:

**Comment by michaelrfraser** [comment]
I have submitted a PR here https://github.com/openlvc/portico/pull/123 in response to this issue.

**Comment by timpokorny** [comment]
Tested and merged.

**Comment by michaelrfraser** [comment]
Looks like I missed one that was pragma'd out on my mac:

```
[cpptask] /home/travis/build/openlvc/portico/codebase/src/cpp/hla13/src/jni/Runtime.cpp: In member function ‘std::pair<std::basic_string<char>, std::basic_string<char> > portico13::Runtime::generateUnixPath(std::string)’:
  [cpptask] /home/travis/build/openlvc/portico/codebase/src/cpp/hla13/src/jni/Runtime.cpp:387:16: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
  [cpptask] At global scope:
  [cpptask] cc1plus: warning: unrecognized command line option "-Wno-write-string" [enabled by default]
```

**Comment by michaelrfraser** [comment]
Submitted PR for the missed transform https://github.com/openlvc/portico/pull/125

**Comment by timpokorny** [comment]
Merge PR above.
